# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\reybe\OneDrive\Escritorio\ysr Control de inventario\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 404)
        MainWindow.setMaximumSize(QtCore.QSize(548, 404))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(548, 404))
        self.centralwidget.setMaximumSize(QtCore.QSize(548, 404))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(548, 404))
        self.frame.setMaximumSize(QtCore.QSize(548, 404))
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_acceder = QtWidgets.QPushButton(self.frame)
        self.btn_acceder.setGeometry(QtCore.QRect(230, 290, 141, 81))
        self.btn_acceder.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"background-color:blue;\n"
"border-radius:24px;")
        self.btn_acceder.setObjectName("btn_acceder")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Hack Nerd Font Mono")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(100, 120, 72, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font-size:14px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font-size:14px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget1 = QtWidgets.QWidget(self.frame)
        self.widget1.setGeometry(QtCore.QRect(400, 120, 108, 111))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txt_user = QtWidgets.QLineEdit(self.widget1)
        self.txt_user.setStyleSheet("border:none;\n"
"border-bottom:2px solid blue;")
        self.txt_user.setObjectName("txt_user")
        self.verticalLayout_3.addWidget(self.txt_user)
        self.txt_password = QtWidgets.QLineEdit(self.widget1)
        self.txt_password.setStyleSheet("border:none;\n"
"border-bottom:2px solid blue;")
        self.txt_password.setObjectName("txt_password")
        self.verticalLayout_3.addWidget(self.txt_password)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_acceder.setText(_translate("MainWindow", "Ingresar"))
        self.label_3.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Usuario"))
        self.label_2.setText(_translate("MainWindow", "Contraseña"))
